version: '3.8'

services:
  api:
    build: .
    container_name: task_manager
    command: /app/wait-for-it.sh db:5432 -- /app/.venv/bin/fastapi run app/main.py --port 80 --host 0.0.0.0
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_URL=postgresql+asyncpg://postgres:postgres@db/task_manager
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: /app/.venv/bin/celery -A app.core.worker.celery_app worker -l info -E
    depends_on:
      - api
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

volumes:
  pgdata:
